%%
%% Autogenerated by Thrift
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(scribe_types).

-include("scribe_types.hrl").

-export([struct_info/1]).
%% struct logEntry

% -record(logEntry, {category, message}).

struct_info('logEntry') ->
  {struct, [{1, string},
  {2, string}]}
;

struct_info('i am a dummy struct') -> undefined.
