%%
%% Autogenerated by Thrift
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(fb303_types).

-include("fb303_types.hrl").

-export([struct_info/1]).
struct_info('i am a dummy struct') -> undefined.
